# Blueprint pour Render
databases:
  - name: yowpainter-db
    databaseName: yowpainter_prod
    plan: free
    user: yowpainter_user

services:
  # Service Web Backend (Docker)
  - type: web
    name: yowpainter-api
    runtime: docker # Utilisation de Docker car Java n'est pas supporté nativement
    plan: free
    region: frankfurt 
    envVars:
      # Note: Le buildCommand et startCommand sont définis dans le Dockerfile
      
      # Configuration de la base de données (Propriétés individuelles)
      - key: DB_HOST
        fromDatabase:
          name: yowpainter-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: yowpainter-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: yowpainter-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: yowpainter-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: yowpainter-db
          property: password

      # Sécurité et Application
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://yowpainter.onrender.com

      # Mail secrets
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
